name: SkyBattle
version: 1.0
main: manaki.plugin.skybattle.SkyBattle
api-version: 1.16
commands:
  skybattle:
    permission: skybattle.admin
    aliases: [sb]
  quit:
    permission: skybattle.player
    aliases: [thoat, out]